import type { NveSourceEntry, NveSourceRef, SourceUse } from "./sourceAnchoredModel";

function source(entry: NveSourceEntry): NveSourceEntry {
  return entry;
}

const VEILEDER_2020 = "NVE Veileder nr. 3/2020, Slipp, måling og dokumentasjon av minstevannføring";
const MVF_2024 = "Retningslinje for registrering av konsesjonspålagte minstevannføringer, vedtatt 12.02.24";
const ELV_2024 = "Retningslinje for registrering av vannføring i elver, vedtatt 12.02.24";

export const nveSourceRegister = {
  NVE_2020_1_3: source({ id: "NVE_2020_1_3", documentTitle: VEILEDER_2020, year: 2020, section: "1.3", sectionTitle: "Innholdet i veilederen", sourceType: "NVE veileder", shortParaphrase: "The guide covers release solutions, measurement, documentation, fish passages, coanda screens, public information, operation, and arrangements NVE may approve.", normativeUse: "Scope boundary for HydroGuide's method-selection and documentation-readiness flow.", notes: "Used as context, not as a standalone user answer." }),
  NVE_2020_1_4_1: source({ id: "NVE_2020_1_4_1", documentTitle: VEILEDER_2020, year: 2020, section: "1.4.1", sectionTitle: "Vassdragslovgivningen", sourceType: "NVE veileder", shortParaphrase: "The concession or decision sets the minimum-flow requirement for the plant.", normativeUse: "HydroGuide must ask for the applicable requirement and must not invent it.", notes: "Missing concession basis is missing documentation." }),
  NVE_2020_1_4_2: source({ id: "NVE_2020_1_4_2", documentTitle: VEILEDER_2020, year: 2020, section: "1.4.2", sectionTitle: "Det er tiltakshavers ansvar å oppfylle gitte krav", sourceType: "NVE veileder", shortParaphrase: "The responsible party must fulfill requirements, store documentation, and present it to NVE.", normativeUse: "Report/system requirement; not a user-facing answer.", notes: "Secure storage is reported as an assumption, not a validation blocker." }),
  NVE_2020_2_6: source({ id: "NVE_2020_2_6", documentTitle: VEILEDER_2020, year: 2020, section: "2.6", sectionTitle: "Sjekkliste for detaljplan", sourceType: "NVE veileder", shortParaphrase: "Detail plans cover release and measurement method, hydraulics, debris and ice, regulation, fish passage, data transfer, control measurements, public information, drawings, and operational follow-up.", normativeUse: "Documentation themes and card structure.", notes: "Only source-backed themes become visible questions." }),
  NVE_2020_3_1: source({ id: "NVE_2020_3_1", documentTitle: VEILEDER_2020, year: 2020, section: "3.1", sectionTitle: "Betydning for valg av arrangement", sourceType: "NVE veileder", shortParaphrase: "Hydrology, climate, physical conditions, size and seasonal pattern of release, operation safety, and accessibility affect arrangement choice.", normativeUse: "Site and operational constraints.", notes: "Avoids generic risk questions." }),
  NVE_2020_4_1: source({ id: "NVE_2020_4_1", documentTitle: VEILEDER_2020, year: 2020, section: "4.1", sectionTitle: "Innledning", sourceType: "NVE veileder", shortParaphrase: "Main release categories include pipe via intake, pipe through dam, gates, opening/notch in dam, and reference to fish passage/coanda.", normativeUse: "Release-solution category question.", notes: "Each category is separately anchored to its detailed section." }),
  NVE_2020_4_2: source({ id: "NVE_2020_4_2", documentTitle: VEILEDER_2020, year: 2020, section: "4.2", sectionTitle: "Rør via inntaket", sourceType: "NVE veileder", shortParaphrase: "Pipe via intake can use intake after rack, dry/frost-free placement, pipe regulation, correct installation, filled pipe, straight run, and service valve considerations.", normativeUse: "Pipe via intake method and pipe-measurement criteria.", notes: "Direct pipe measurement is recommended only when documented criteria are satisfied." }),
  NVE_2020_4_3: source({ id: "NVE_2020_4_3", documentTitle: VEILEDER_2020, year: 2020, section: "4.3", sectionTitle: "Rør gjennom dam", sourceType: "NVE veileder", shortParaphrase: "Pipe through dam requires low placement, capacity margin, avoidance of vortices/air intake, submerged/protected pipe, sediment/blocking handling, and warns against theoretical-only documentation.", normativeUse: "Dam-pipe criteria and theoretical-only warning.", notes: "Theoretical calculations alone cannot produce ready status." }),
  NVE_2020_4_4: source({ id: "NVE_2020_4_4", documentTitle: VEILEDER_2020, year: 2020, section: "4.4", sectionTitle: "Luker", sourceType: "NVE veileder", shortParaphrase: "Gate solutions can suit larger releases but require access, climate, power, downstream measurement where possible, backup, and winter operation handling.", normativeUse: "Gate criteria.", notes: "Gate recommendations depend on documented measurement/control criteria." }),
  NVE_2020_4_5: source({ id: "NVE_2020_4_5", documentTitle: VEILEDER_2020, year: 2020, section: "4.5", sectionTitle: "Utsparing i overløpsterskel i dam", sourceType: "NVE veileder", shortParaphrase: "Opening/notch in dam can suit larger releases but has clogging/icing risk, profile/capacity requirements, and sensitivity to water-level variation.", normativeUse: "Opening/notch criteria.", notes: "Low-water capacity and clogging/icing handling are required criteria." }),
  NVE_2020_5_1: source({ id: "NVE_2020_5_1", documentTitle: VEILEDER_2020, year: 2020, section: "5.1", sectionTitle: "Inntak med fiskepassasjer", sourceType: "NVE veileder", shortParaphrase: "Fish passage can govern release and measurement; measurement must not create barriers or delay fish.", normativeUse: "Fish-passage release and measurement criteria.", notes: "Barrier/delay criteria are rejection criteria." }),
  NVE_2020_5_2: source({ id: "NVE_2020_5_2", documentTitle: VEILEDER_2020, year: 2020, section: "5.2", sectionTitle: "Inntak med overløpsrister / coandarister", sourceType: "NVE veileder", shortParaphrase: "Coanda/tyrolean screens require attention to return point, dry stretch, pools/wetted area, low head, takeoff point, and air entrainment.", normativeUse: "Coanda/tyrolean criteria.", notes: "Air entrainment and low fall are explicit decision inputs." }),
  NVE_2020_6_1: source({ id: "NVE_2020_6_1", documentTitle: VEILEDER_2020, year: 2020, section: "6.1", sectionTitle: "Hovedprinsipper for måling av vannføring", sourceType: "NVE veileder", shortParaphrase: "Main measurement principles are flow measurement in pipe and water level with rating curve; registration, storage, and presentation to NVE are required.", normativeUse: "Measurement-principle and report/system requirements.", notes: "Secure storage is not a user answer." }),
  NVE_2020_6_2: source({ id: "NVE_2020_6_2", documentTitle: VEILEDER_2020, year: 2020, section: "6.2", sectionTitle: "Måling av vannføring i rør", sourceType: "NVE veileder", shortParaphrase: "Pipe measurement needs suitable sensors, full pipe, air handling, downstream valve/venting/swan-neck geometry, calibration, and supplier constraints.", normativeUse: "Pipe-flow measurement criteria.", notes: "Meter-specific options must inherit this source." }),
  NVE_2020_6_3: source({ id: "NVE_2020_6_3", documentTitle: VEILEDER_2020, year: 2020, section: "6.3", sectionTitle: "Beregning av vannføring basert på måling av vannstand", sourceType: "NVE veileder", shortParaphrase: "Water-level measurement requires rating curve, downstream profile, electronic registration, control measurement, and no fish migration barrier.", normativeUse: "Water-level and downstream-profile criteria.", notes: "Used across dam/gate/opening/fish solutions." }),
  NVE_2020_6_3_3: source({ id: "NVE_2020_6_3_3", documentTitle: VEILEDER_2020, year: 2020, section: "6.3.3", sectionTitle: "Vannføringsmåling i naturlig elveprofil", sourceType: "NVE veileder", shortParaphrase: "Natural profiles need stable and unambiguous water-level/flow relationship, stable control profile, good resolution, and handling of ice/flood/sediment changes.", normativeUse: "Natural-profile criteria.", notes: "Missing rating curve or unstable profile prevents ready status." }),
  NVE_2020_6_3_4: source({ id: "NVE_2020_6_3_4", documentTitle: VEILEDER_2020, year: 2020, section: "6.3.4", sectionTitle: "Kunstige måleprofil", sourceType: "NVE veileder", shortParaphrase: "Artificial profiles are alternatives when natural profiles are unsuitable and require precise construction, standards, control measurements, and representative sensors.", normativeUse: "Artificial-profile criteria.", notes: "Use only when artificial profile is selected or natural profile is unsuitable." }),
  NVE_2020_7: source({ id: "NVE_2020_7", documentTitle: VEILEDER_2020, year: 2020, section: "7", sectionTitle: "Informasjon om minstevannføringen på stedet", sourceType: "NVE veileder", shortParaphrase: "Public control, display, and signage are information requirements.", normativeUse: "Separate public-information/report module.", notes: "Not mixed into method selection." }),
  NVE_2020_8: source({ id: "NVE_2020_8", documentTitle: VEILEDER_2020, year: 2020, section: "8", sectionTitle: "Oppfølging i driftsfasen", sourceType: "NVE veileder", shortParaphrase: "Operation requires follow-up, internal control, alarms, routine checks, calibration, post-flood/ice checks, maintenance, and control measurements.", normativeUse: "Operation and control criteria.", notes: "Used for site/operation constraints and report assumptions." }),
  NVE_2020_9: source({ id: "NVE_2020_9", documentTitle: VEILEDER_2020, year: 2020, section: "9", sectionTitle: "Oppsummering - arrangement NVE godkjenner", sourceType: "NVE veileder", shortParaphrase: "Summary matrix links accepted arrangements, associated measurement methods, documentation, remarks, and public-control methods.", normativeUse: "Method candidate source and documentation matrix.", notes: "All method candidates cite this when part of the accepted arrangement set." }),
  NVE_2024_MVF_1_3: source({ id: "NVE_2024_MVF_1_3", documentTitle: MVF_2024, year: 2024, section: "1-3", sectionTitle: "Formål, omfang, ansvar og myndighet", sourceType: "NVE retningslinje", shortParaphrase: "Standardized methods, data delivery, accuracy, scope, and responsibility for sufficient data quality.", normativeUse: "Documentation-readiness scope.", notes: "Supports project requirement and report status." }),
  NVE_2024_MVF_4: source({ id: "NVE_2024_MVF_4", documentTitle: MVF_2024, year: 2024, section: "4", sectionTitle: "Registrering av minstevannføring", sourceType: "NVE retningslinje", shortParaphrase: "Minimum flow can be documented by direct/indirect pipe measurement or water-level registration with downstream rating curve.", normativeUse: "Measurement method source.", notes: "Used with 2020 measurement sections." }),
  NVE_2024_MVF_4_1: source({ id: "NVE_2024_MVF_4_1", documentTitle: MVF_2024, year: 2024, section: "4.1", sectionTitle: "Instrumentering, målefrekvens og nøyaktighet", sourceType: "NVE retningslinje", shortParaphrase: "Minimum hourly frequency, +/-5 percent accuracy at minimum-flow release, 97 percent correct/complete registrations, continuous operation/data access, and backup where relevant.", normativeUse: "Universal non-interactive obligation.", notes: "Handled as implicit report and AI narrative requirements, not as user-facing questions or validation blockers." }),
  NVE_2024_MVF_4_2: source({ id: "NVE_2024_MVF_4_2", documentTitle: MVF_2024, year: 2024, section: "4.2", sectionTitle: "Vannføring i rør", sourceType: "NVE retningslinje", shortParaphrase: "Pipe measurement uses sensors on/in pipe; theoretical pipe capacity based on dam/intake level needs manual control measurement; calibration and third-year control are required.", normativeUse: "Pipe-measurement documentation criteria.", notes: "Theoretical-only documentation is not enough." }),
  NVE_2024_MVF_4_3: source({ id: "NVE_2024_MVF_4_3", documentTitle: MVF_2024, year: 2024, section: "4.3", sectionTitle: "Beregning av vannføring basert på måling av vannstand", sourceType: "NVE retningslinje", shortParaphrase: "Water-level based calculation requires an unambiguous relationship, rating curve submission, and operation under river-flow guideline.", normativeUse: "Water-level documentation criteria.", notes: "Used for downstream profile methods." }),
  NVE_2024_MVF_4_3_1: source({ id: "NVE_2024_MVF_4_3_1", documentTitle: MVF_2024, year: 2024, section: "4.3.1", sectionTitle: "Naturlig elveprofil", sourceType: "NVE retningslinje", shortParaphrase: "Natural profiles need sufficient measurements, a valid curve with quality around minimum flow, no flow reduction below requirement without NVE permission, and new measurements when relationships change.", normativeUse: "Natural-profile documentation criteria.", notes: "Supports rating curve and profile-change criteria." }),
  NVE_2024_MVF_4_3_2: source({ id: "NVE_2024_MVF_4_3_2", documentTitle: MVF_2024, year: 2024, section: "4.3.2", sectionTitle: "Kunstige måleprofiler", sourceType: "NVE retningslinje", shortParaphrase: "Artificial profiles at small flows need stability, water-level accuracy, and documentation of +/-5 percent accuracy with at least three measurements around required release.", normativeUse: "Artificial-profile verification criteria.", notes: "Damage/change triggers new controls." }),
  NVE_2024_MVF_4_4: source({ id: "NVE_2024_MVF_4_4", documentTitle: MVF_2024, year: 2024, section: "4.4", sectionTitle: "Slipp via luker - vannføring basert på teoretiske beregninger", sourceType: "NVE retningslinje", shortParaphrase: "NVE usually requires a downstream measuring point when flow is released via pipe through dam, gates, or opening in dam.", normativeUse: "Dam/gate/opening downstream-measurement requirement.", notes: "Prevents theoretical-only ready decisions." }),
  NVE_2024_MVF_4_5: source({ id: "NVE_2024_MVF_4_5", documentTitle: MVF_2024, year: 2024, section: "4.5", sectionTitle: "Kontroll av minstevannføringsstasjoner", sourceType: "NVE retningslinje", shortParaphrase: "Periodic controls, annual main control, third-year control near minimum-flow requirement, and all seasonal requirements controlled over three years.", normativeUse: "Control routine documentation.", notes: "Report/control criteria." }),
  NVE_2024_ELV_4_2_1: source({ id: "NVE_2024_ELV_4_2_1", documentTitle: ELV_2024, year: 2024, section: "4.2.1", sectionTitle: "Målesystem", sourceType: "NVE retningslinje", shortParaphrase: "Automatic water-level measurement should cover the interval, use three decimals, stay within +/-1 cm total instrument uncertainty, operate continuously, and normally use two sensors.", normativeUse: "Water-level station instrumentation criteria.", notes: "Used for water-level measurement card." }),
  NVE_2024_ELV_4_3: source({ id: "NVE_2024_ELV_4_3", documentTitle: ELV_2024, year: 2024, section: "4.3", sectionTitle: "Kontroll av vannstand", sourceType: "NVE retningslinje", shortParaphrase: "Reference point/bolt, reference height, staff gauge/control reading, and sensor/reference control.", normativeUse: "Water-level control criteria.", notes: "Supports report/control assumptions." }),
  NVE_2024_ELV_4_4: source({ id: "NVE_2024_ELV_4_4", documentTitle: ELV_2024, year: 2024, section: "4.4", sectionTitle: "Vannføringsmålinger", sourceType: "NVE retningslinje", shortParaphrase: "Measurements should follow standards, use competent personnel and calibrated instruments, and handle ice backwater.", normativeUse: "Control measurement criteria.", notes: "Supports natural/profile control." }),
  NVE_2024_ELV_4_5: source({ id: "NVE_2024_ELV_4_5", documentTitle: ELV_2024, year: 2024, section: "4.5", sectionTitle: "Vannføringskurve", sourceType: "NVE retningslinje", shortParaphrase: "Rating-curve establishment, NVE approval, natural-profile measurements, hydraulic model support, artificial-profile verification, three-year control, and curve revision when relationships change.", normativeUse: "Rating curve and profile verification criteria.", notes: "Used by natural and artificial profile cards." }),
  NVE_2024_ELV_4_6: source({ id: "NVE_2024_ELV_4_6", documentTitle: ELV_2024, year: 2024, section: "4.6", sectionTitle: "Kontroll av vannføringsstasjon", sourceType: "NVE retningslinje", shortParaphrase: "Annual and periodic controls cover instruments, power supply, sensors, remote-transfer equipment, water-level accuracy, debris/ice control, and inspection intervals.", normativeUse: "Operation/control and documentation-readiness criteria.", notes: "Used for site constraints and control routine requirements." }),
  NVE_2024_ELV_4_7: source({ id: "NVE_2024_ELV_4_7", documentTitle: ELV_2024, year: 2024, section: "4.7", sectionTitle: "Feilutbedring", sourceType: "NVE retningslinje", shortParaphrase: "97 percent operative/correct water-level registration, rapid correction, notification if repair exceeds one week, temporary instrumentation/manual readings.", normativeUse: "Completeness and fault-handling criteria.", notes: "Supports 97 percent readiness status." })
} as const satisfies Record<string, NveSourceEntry>;

export type NveSourceId = keyof typeof nveSourceRegister;

export function sourceRef(id: string, use: SourceUse): NveSourceRef {
  const entry = nveSourceRegister[id as NveSourceId];
  if (!entry) {
    throw new Error(`Unknown NVE source id: ${id}`);
  }

  return {
    id: entry.id,
    documentTitle: entry.documentTitle,
    year: entry.year,
    section: entry.section,
    sectionTitle: entry.sectionTitle,
    use,
    shortParaphrase: entry.shortParaphrase
  };
}
